#spring.application.name=springBootTest

# 컨트롤러에서 호출할 뷰 페이지 경로
#spring.mvc.view.prefix=/WEB-INF/views/

# 컨트롤러에서 호출할 뷰 페이지 접미사(파일확장자명)
#spring.mvc.view.suffix=.jsp

--- # Start

--- # change port
server:
  port: 8085

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false # 소스 reload
    prefix: file:src/main/resources/templates # classpath:/templates
    suffix: .html

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/boot_study
    username: boot
    password: boot

--- #
spring:
  jpa:
    hibernate:
      ddl-auto: none #update
    properties:
      hibernate:
        show_sql : true
        format_sql: true